version: "3.9"

services:
  db:
    image: mysql
    container_name: zupch
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
    - zupch_data:/var/lib/mysql

volumes:
  zupch_data:

