server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datatest
    username: user0
    password: root
    driver-class-name:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
