server:
  port: 8081 #Caso queira trocar a porta, so trocar !

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datatest
    username: postgres
    password: 123456
#    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true