server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datatest
    username: postgres
    password: 123456
#    driver-class-name:

  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true